### ISSUE TITLE
Questions for citation format and data access

### ISSUE THREAD

**Issue by eqo295** [iDPI-Umass/reddit-map#50]
### Pitch

I am currently a graduate student specializing in Communication and am in the process of writing my thesis. My research has led me to have a keen interest in the content displayed on the Reddit map page.

Would it be possible for me to obtain the data that underpins this map? Additionally, could you guide me on how to appropriately cite this data in my academic work?

Your support would be invaluable to my research. I genuinely appreciate your consideration and assistance in this matter.

P.S. I have reached out through this channel as I found it challenging to locate an official point of contact.

### Motivation

Contribute to further research using this page.

**Comment by kevinyzheng** [comment]
Thanks for your message! I'm Kevin, researcher at UMass Amherst and the community manager for the Reddit Map project. 

When it comes to citing the map, we'd ask that you cite this preprint that our research team has shared on arXiv: [https://arxiv.org/abs/2309.14259](https://arxiv.org/abs/2309.14259)

The preprint explains our approach to the data and preprocessing that underlies the clustering that is seen on [RedditMap.social](https://redditmap.social). The Python module for subreddit data processing and clustering is available here: [https://github.com/UMassCDS/IHOP-Reddit/](https://github.com/UMassCDS/IHOP-Reddit/). If you have questions, please file another issue on GitHub and we'll get back to you when we can (we are an academic lab with many projects and limited resources, so our response times may be slow). 

The Reddit comments dataset that our team used comes directly from Pushshift, and ongoing changes with Reddit's API and Pushshift's agreements with Reddit are impacting our ability to process data on a regular basis as we had intended for this project. We cannot provide you with Pushshift's comments data, but you may be able to obtain them on your own at [https://pushshift.io/signup](https://pushshift.io/signup).
